#!/usr/bin/env python3
"""
Landmark Database: stores and manages detected landmark information.

Classes
-------
LandmarkEntry
    Dataclass representing one detected landmark.
LandmarkDatabase
    In-memory store with add / update / query operations.
"""

import math
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple


@dataclass
class LandmarkEntry:
    """Represents a single detected landmark in the environment.

    Attributes
    ----------
    landmark_id : str
        Unique identifier generated by the database.
    label : str
        Object class name (e.g. ``'stop_sign'``).
    x, y, z : float
        Position in the reference frame used at detection time.
    confidence : float
        Highest detection confidence seen so far (0–1).
    detection_count : int
        Number of times this landmark has been (re-)detected.
    first_seen : float
        Unix timestamp of the first detection.
    last_seen : float
        Unix timestamp of the most recent detection.
    attributes : dict
        Arbitrary key/value metadata (e.g. image coordinates, colour).
    """

    landmark_id: str
    label: str
    x: float
    y: float
    z: float
    confidence: float
    detection_count: int = 1
    first_seen: float = field(default_factory=time.time)
    last_seen: float = field(default_factory=time.time)
    attributes: Dict = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def distance_to(self, x: float, y: float, z: float) -> float:
        """Return the Euclidean distance from this landmark to (x, y, z)."""
        return math.sqrt(
            (self.x - x) ** 2 + (self.y - y) ** 2 + (self.z - z) ** 2
        )

    def to_dict(self) -> Dict:
        """Serialise this entry to a plain dictionary (JSON-safe)."""
        return {
            'landmark_id': self.landmark_id,
            'label': self.label,
            'position': {'x': self.x, 'y': self.y, 'z': self.z},
            'confidence': self.confidence,
            'detection_count': self.detection_count,
            'first_seen': self.first_seen,
            'last_seen': self.last_seen,
            'attributes': self.attributes,
        }


class LandmarkDatabase:
    """In-memory database for storing and managing detected landmarks.

    All operations are thread-*unsafe* – callers are responsible for
    synchronisation when used from multiple threads.

    Parameters
    ----------
    position_alpha : float
        Low-pass filter coefficient used when blending a new position
        observation into an existing landmark.  Must be in (0, 1].
        A value of 1.0 means no smoothing (use the latest observation
        directly); lower values give more weight to the historic average.
        Defaults to ``0.3``.

    Example
    -------
    >>> db = LandmarkDatabase()
    >>> lid = db.add_landmark('stop_sign', x=1.0, y=2.0, z=0.0, confidence=0.9)
    >>> db.update_landmark(lid, x=1.05, y=2.0, z=0.0, confidence=0.92)
    >>> entry = db.get_landmark(lid)
    >>> matches = db.query_by_label('stop_sign')
    """

    def __init__(self, position_alpha: float = 0.3) -> None:
        if not (0.0 < position_alpha <= 1.0):
            raise ValueError('position_alpha must be in the range (0, 1]')
        self._alpha = position_alpha
        self._landmarks: Dict[str, LandmarkEntry] = {}
        self._counter: int = 0

    # ------------------------------------------------------------------
    # Mutating operations
    # ------------------------------------------------------------------

    def add_landmark(
        self,
        label: str,
        x: float,
        y: float,
        z: float,
        confidence: float,
        attributes: Optional[Dict] = None,
    ) -> str:
        """Add a new landmark and return its generated ID.

        Parameters
        ----------
        label : str
            Object class name.
        x, y, z : float
            3-D position in the reference frame.
        confidence : float
            Detection confidence (0–1).
        attributes : dict, optional
            Extra metadata to attach.

        Returns
        -------
        str
            The newly assigned ``landmark_id``.
        """
        landmark_id = f'{label}_{self._counter}'
        self._counter += 1
        self._landmarks[landmark_id] = LandmarkEntry(
            landmark_id=landmark_id,
            label=label,
            x=x,
            y=y,
            z=z,
            confidence=confidence,
            attributes=dict(attributes) if attributes else {},
        )
        return landmark_id

    def update_landmark(
        self,
        landmark_id: str,
        x: float,
        y: float,
        z: float,
        confidence: float,
        attributes: Optional[Dict] = None,
    ) -> bool:
        """Update an existing landmark's position and confidence.

        Position is blended with a low-pass filter (α = 0.3) to reduce
        noise from individual detections.

        Returns
        -------
        bool
            ``True`` if the landmark was found and updated.
        """
        entry = self._landmarks.get(landmark_id)
        if entry is None:
            return False

        alpha = self._alpha
        entry.x = alpha * x + (1.0 - alpha) * entry.x
        entry.y = alpha * y + (1.0 - alpha) * entry.y
        entry.z = alpha * z + (1.0 - alpha) * entry.z
        entry.confidence = max(entry.confidence, confidence)
        entry.detection_count += 1
        entry.last_seen = time.time()
        if attributes:
            entry.attributes.update(attributes)
        return True

    def add_or_update(
        self,
        label: str,
        x: float,
        y: float,
        z: float,
        confidence: float,
        merge_radius: float = 1.5,
        attributes: Optional[Dict] = None,
    ) -> Tuple[str, bool]:
        """Add a new landmark **or** update the nearest existing one.

        If an existing landmark of the same *label* is within
        *merge_radius* metres of the given position, its entry is
        updated rather than creating a duplicate.

        Returns
        -------
        tuple[str, bool]
            ``(landmark_id, was_updated)`` where *was_updated* is
            ``True`` when an existing entry was merged.
        """
        nearest: Optional[LandmarkEntry] = None
        nearest_dist = float('inf')

        for entry in self._landmarks.values():
            if entry.label == label:
                d = entry.distance_to(x, y, z)
                if d < nearest_dist:
                    nearest_dist = d
                    nearest = entry

        if nearest is not None and nearest_dist <= merge_radius:
            self.update_landmark(
                nearest.landmark_id, x, y, z, confidence, attributes
            )
            return nearest.landmark_id, True

        new_id = self.add_landmark(label, x, y, z, confidence, attributes)
        return new_id, False

    def remove_landmark(self, landmark_id: str) -> bool:
        """Remove a landmark by ID.

        Returns
        -------
        bool
            ``True`` if the landmark existed and was removed.
        """
        if landmark_id in self._landmarks:
            del self._landmarks[landmark_id]
            return True
        return False

    def clear(self) -> None:
        """Remove all landmarks and reset the internal ID counter."""
        self._landmarks.clear()
        self._counter = 0

    # ------------------------------------------------------------------
    # Query operations
    # ------------------------------------------------------------------

    def get_landmark(self, landmark_id: str) -> Optional[LandmarkEntry]:
        """Return the landmark with *landmark_id*, or ``None``."""
        return self._landmarks.get(landmark_id)

    def get_all(self) -> List[LandmarkEntry]:
        """Return a list of all stored landmarks."""
        return list(self._landmarks.values())

    def query_by_label(self, label: str) -> List[LandmarkEntry]:
        """Return all landmarks whose label matches *label*."""
        return [e for e in self._landmarks.values() if e.label == label]

    def query_near(
        self,
        x: float,
        y: float,
        z: float,
        radius: float,
    ) -> List[LandmarkEntry]:
        """Return all landmarks within *radius* metres of (x, y, z)."""
        return [
            e for e in self._landmarks.values()
            if e.distance_to(x, y, z) <= radius
        ]

    # ------------------------------------------------------------------
    # Special methods
    # ------------------------------------------------------------------

    def __len__(self) -> int:
        return len(self._landmarks)

    def __repr__(self) -> str:
        return f'LandmarkDatabase(count={len(self)})'
